#!/bin/bash

City=""
lat=""
lon=""

get_name(){

  json_data=$(curl -s "https://nominatim.openstreetmap.org/search.php?q=$1&format=jsonv2")
  
  City=$(echo $json_data | jq '.[0].name')

  lat=$(echo $json_data | jq '.[0].lat')

  lon=$(echo $json_data | jq '.[0].lon')

}

load_data(){

  data=$(curl -s "https://danepubliczne.imgw.pl/api/data/synop/")

  echo $data | jq '.[].stacja' | while read -r station; do
    if [ "$debug" -eq 1 ]; then
      echo "Station: $station"
    fi
  done

}

city=""
debug=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --city)
      city="$2"
      shift 2
      ;;
    --debug)
      debug=1
      shift
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

load_data

if [ -z "$city" ]; then
  echo -e "\033[31mExpected non-empty --city argument\033[0m"
  exit 1
fi

get_name $city

if [ "$debug" -eq 1 ]; then
  echo "City: $City"
  echo "lat: $lat"
  echo "lon: $lon"

fi

echo $city
